apiVersion: apps/v1
kind: Deployment
metadata:
  name: Draw
  labels:
    app: Draw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Draw
  template:
    metadata:
      labels:
        app: Draw
    spec:
      containers:
        - name: Draw
          image: username/Draw:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5